### ISSUE TITLE
Automatically publish extension to marketplace.visualstudio.com

### ISSUE THREAD

**Issue by heku** [madskristensen/ExtensionScripts#16]
Hi Mads, 

Thank you for your great work bring us lots of great extensions. As you are maintaining lots of extensions, may I know how you published them to https://marketplace.visualstudio.com? I know this repo contains script to publish vsix to http://vsixgallery.com, but I had to manually upload vsix to the official marketplace finally. 

Any suggestion is appreciated, thank you.

**Comment by madskristensen** [comment]
Though there now is a command line tool to upload to the Marketplace, I still do that part manually

**Comment by heku** [comment]
Well, I thought there was some automatic way, thanks for reply.
