### ISSUE TITLE
Vsix-PushArtifacts and Vsix-PublishToGallery crash on encountering a folder that ends with .Vsix

### ISSUE THREAD

**Issue by HellBrick** [madskristensen/ExtensionScripts#5]
Here's what happens when `Vsix-PushArtifacts` is invoked when vsix project folder is called `Something.Vsix`: https://ci.appveyor.com/project/HellBrick/hellbrick-refactorings/build/1.2.4#L37

I have a partial fix that you might find useful at https://github.com/HellBrick/ExtensionScripts/commit/6f9d360fc852ffe623b120318ee3cb4c764c1dc5. It doesn't fix `Vsix-PublishToGallery` though (which suffers from the same problem): I've found it's easier to just do `Vsix-PushArtifacts -publishToGallery` instead of messing with `Vsix-PublishToGallery` =)

**Comment by madskristensen** [comment]
You can specify the path to the .vsix as a parameter to both those function, which should fix it. A general fix would be good to have though
